[pytest]
pythonpath=.
testpaths =
    backend/api/tests
    backend/api/tests/routertests
    backend/data/cleansing_scripts
    test_scripts
python_files = test_*.py *_test.py tests_*.py *_tests.py
python_classes = Test*
python_functions = test_* *_test tests_* *_tests